sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.2

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

matrix:
  exclude:
    - rvm: 1.9.3
      env: DB=mysql
    - rvm: 1.9.3
      env: DB=sqlite
    - rvm: 2.0.0
      env: DB=mysql
    - rvm: 2.0.0
      env: DB=sqlite
    - rvm: 2.1.5
      env: DB=mysql
    - rvm: 2.1.5
      env: DB=sqlite

gemfile: Gemfile.ci

bundler_args: --path=vendor/bundle --without heroku

cache: bundler

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - sh -c "cp config/database.$DB.yml config/database.yml"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database fat_free_crm_test;' -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -e 'create database fat_free_crm_test;'; fi"
  - sh -c "RAILS_ENV=test bundle exec rake db:schema:load"

# Run specs
script: "RAILS_ENV=test bundle exec rake"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/859260451e154d78c1be
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
